### ISSUE TITLE
Question/feature-request: Specifying list of local variables before running `CurrentRuby.parse`

### ISSUE THREAD

**Issue by waterlink** [whitequark/parser#200]
Hi, thanks for the gem! It is great!

I'm trying to parse partial code and I do know that certain names are defined as local variables, though they are not in this part of the code.

Example:

```ruby
Parser::CurrentRuby.parse("hello")
# => (send nil :hello)
```

I want to somehow be able to pass a list of local variables in:

```ruby
Parser::CurrentRuby.parse("hello", [:hello, :world])
# => (lvar :hello)
```

Currently I have to do this ugly workaround:

```ruby
Parser::CurrentRuby.parse("(hello = hello; hello)")
# => (begin (lvasgn :hello (lvar :hello)) (lvar :hello))
```

Is there a possibility to do it currently in any way? Would it be discouraged usage of the gem or not?

If both are false, do you mind me jumping in and sending a PR with implementation of optional argument with list of local variables to `#parse`, or you might see a better API for that?

Cheers!

**Comment by mbj** [comment]
@waterlink you could also just manually "declare" the lvars before the actual partial you are parsing:

```ruby
code = "lvar_a = lvar_b = lvar_c = nil; #{your_partial_code}"
Parser::CurrentRuby.parse(code)
```

Than you could "filter" the AST for the lvar "declarations" away and process the reminder as the partial source.

**Comment by mbj** [comment]
LOL, my fault I was not reading you already *have* the workaround. Ignore **all* my noise here.

**Comment by alex-fedorov** [comment]
I see in code `StaticEnvironment` which holds all the variable definitions, but it is encapsulated and there is no access to it from outside.

The core of the problem is that I already have AST, but I need to get a chunk of this AST, convert it to string representation, pass these strings to a string template, which will return final code chunk and at this point I want to be able to get it back to my AST replacing the original chunk. Used variables are defined outside of this chunk, so I can't just assign them to `nil`. And I don't control their names, so I can't name them specially to "filter" them out afterwards, unfortunately.

**Comment by whitequark** [comment]
Yes, `StaticEnvironment` is the right way. Just instantiate the parser via `new` and then access the environment via its `static_env` attribute. This is the recommended way.

**Comment by waterlink** [comment]
Ah, I see. There is an example in readme. And there one would instantiate `Source::Buffer` too. Issue resolved, closing.

**Comment by waterlink** [comment]
@whitequark @mbj Thanks for your help!
