### ISSUE TITLE
encoding detection breaks in locale "C" with UTF-8 source files

### ISSUE THREAD

**Issue by cabo** [whitequark/parser#208]
Please see https://github.com/YorickPeterse/ruby-lint/issues/154 for a description and the detailed test case.

**Comment by whitequark** [comment]
oh ffs.

**Comment by whitequark** [comment]
No, there is no bug in Parser. `reencode_string` is clearly documented as:
> If `input` does not contain BOM or magic encoding comment, it is kept in the original encoding.

This is done since Parser::Source::Buffer has no idea what parser will it be used with, and it makes no sense to attempt to fall back to anything except the original encoding of that string.

In Parser, this logic is handled in Parser::Base.parse_with_comments (the class method):
```
    def self.parse_with_comments(string, file='(string)', line=1)
      parser = default_parser
      source_buffer = setup_source_buffer(file, line, string, parser.default_encoding)
      parser.parse_with_comments(source_buffer)
    end

    def self.setup_source_buffer(file, line, string, encoding)
      if string.respond_to? :force_encoding
        string = string.dup.force_encoding(encoding)
      end
      # snip
```

Thus, ruby-lint should be fixed to use the API appropriately.

**Comment by cabo** [comment]
You are, of course, correct; sorry for my confusion.
Pull request to ruby-lint is submitted.
