### ISSUE TITLE
Stabby lambda parsed as a method call

### ISSUE THREAD

**Issue by JoshCheek** [whitequark/parser#212]
Not sure this is a bug, but it's definitely not what I expected:

## Versions

```
$ ruby-parse -v
ruby-parse based on parser version 2.2.3.0

$ ruby -v
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin13]
```

## Stabby Lambda

```
$ ruby-parse -e '->(){}'
(block
  (send nil :lambda)
  (args) nil)
```

## Lambda method call

```
$ ruby-parse -e 'lambda{}'
(block
  (send nil :lambda)
  (args) nil)
```

## Implications

This implies that we can override `lambda` to change the behaviour, but it does not appear to be so:

```ruby
singleton_class.ancestors.each do |klass|
  klass.class_eval do
    def lambda
      Proc.new { 123 }
    end
  end
end

->() { 456 }.call # => 456
```

**Comment by whitequark** [comment]
So... what you're saying is correct in 2.0 and later:
```
> puts RubyVM::InstructionSequence.new('->{}').disasm                                                                                            
== disasm: <RubyVM::InstructionSequence:<compiled>@<compiled>>==========                                                                                      
0000 trace            1                                               (   1)                                                                                  
0002 putspecialobject 1                                                                                                                                       
0004 send             <callinfo!mid:lambda, argc:0, block:block in <compiled>, FCALL>                                                                         
0006 leave                                                                           
```
But this has not been always correct! In 1.9.3:
```
== disasm: <RubyVM::InstructionSequence:<compiled>@<compiled>>==========
0000 trace            1                                               (   1)
0002 putspecialobject 1
0004 send             :lambda, 0, block in <compiled>, 8, <ic:0>
0010 leave            
```

**Comment by whitequark** [comment]
Sorry, no, that's not quite it. Even 1.9.3 does the `putspecialobject 1`, which is the `RubyVM::FrozenCore` object (it's not exposed to Ruby anyhow). But 1.9.2 does not!
```
== disasm: <RubyVM::InstructionSequence:<compiled>@<compiled>>==========
0000 trace            1                                               (   1)
0002 putnil           
0003 send             :lambda, 0, block in <compiled>, 8, <ic:0>
0009 leave            
```
And indeed:
```
[1] pry(main)> module Kernel; def lambda(*); end; end
=> nil
[2] pry(main)> ->{}
=> nil                                                                                                                                                        
[3] pry(main)> RUBY_VERSION
=> "1.9.2"                                                                                                                                                    ```

**Comment by whitequark** [comment]
Digging deeper, it seems I have mindlessly brought over this convention from ruby_parser--1.9.3 was certainly out already when I wrote Parser, and I should have known better. Indeed, this is what ruby_parser does:
```
> Ruby19Parser.new.parse('->{}')
=> s(:iter, s(:call, nil, :lambda), 0)
```
It would not be fair to blame ruby_parser though, as 1.9 support in ruby_parser was done before 1.9.3 was out. I should report a bug against that, too.

As per Parser itself... well. Parser's own convention requires that all semantic differences be reflected in AST structure differences; just locations are not enough. This is totally a breaking change though, so we can't just do it.

At least, once it is done (somehow), the new structure is obvious: `(lambda (args) nil)`.

**Comment by whitequark** [comment]
So, how do we migrate?

**Comment by JoshCheek** [comment]
Seems like plan it for the next major release. In the interim, if it's not a lot of effort, you could have it be a feature flag the operator can opt into, but which defaults to off so as to avoid disruption. If it is a lot of effort, though, I might be the only one who cares about it, and it's not that big of a deal to me (it's straightforward enough to convert in post-processing, and really I have more pressing priorities).

**Comment by JoshCheek** [comment]
I'm probably not the only one who cares. If you see `->` you know that is a lambda, whereas the send might not be a lambda. If anyone is trying to do AST level optimization, I'd expect them to care about stuff like that. But then again, they haven't come filing issues, so maybe no one is doing that sort of thing.

**Comment by whitequark** [comment]
Ok, so to keep the AST compatibility guarantee, the idea is as follows:

  * add `Parser::Builders::Default.emit_lambda = true`
  * give downstream time to adapt to it
  * add a warning every time a `Parser::Builder::Default` is instantiated with `emit_lambda == false` urging to upgrade

Unfortunately it looks like we can never remove the old behavior unless we're willing to silently break downstream in at least _some_ circumstances, and the setter itself can never be removed at all.

cc @mbj @bbatsov

**Comment by mbj** [comment]
my 2c:

I'm totally fine with breaking changes. Its the way of live. Feeding holy cow of backwards compatibility creates so much complexity and friction in the overall process. IMO huge crapyness parts of Ruby are from keeping certain APIs stable prematurely.

So feel free to emit the new lambda without even deprecation ;)

I realize this contradicts your current version policy. But as ruby syntax is very hard to implement, since there is no formal definition: You simply *cannot* decided you actually implemented the ruby syntax or a sub/superset.

As you can never be sure, binding your AST format to the ruby version leads to the current problem. IMO you should consider to lift this constraint for being able to bump the major version on breaking changes like this.

So regardless what route you go (major version bump, deprectation + option, incompatible release without major bump): I'm fine. This is ruby. This is pain. And not your fault.

**Comment by bbatsov** [comment]
I totally agree with @mbj. I understand your desire to impose no compatibility issues to clients, but I'm totally fine with dealing with an occasional breakage in the name of progress. 

I believe that the current versioning scheme is a big mistake and we should simply decouple the parser version from the Ruby version - this would make it easy to bump the major version and we wouldn't be in such binds.

**Comment by whitequark** [comment]
I've no desire to bump major version over this anyway; I don't think it should ever be bumped as parser is a largely finished project.

**Comment by mbj** [comment]
> I've no desire to bump major version over this anyway; I don't think it should ever be bumped as parser is a largely finished project.

Than feel free to simply release a minor version bump with no deprecation.

**Comment by bbatsov** [comment]
A version is just a version - it's not an indication how finished or unfinished some project is. So many people interpret those differently, which really makes fast and hard rules somewhat arbitrary. I'm not saying you should release a major version because of this, I'm saying that releasing major versions is not a big deal and shouldn't be avoided at all costs.

**Comment by whitequark** [comment]
Replace "major version" with "breaking change" above and what I want to say stays same.

**Comment by mbj** [comment]
Current version policy makes it hard to encode breaking changes into the version number. Major version: bound by ruby, minor version assumed by people to be semver compatible (because the policy does NOT include there might be breaking changes here).

IMO we ideally want a breaking change. So how to encode it? and how to document it for the future? I'm fine to say: Parsers major number is not changing (or changes with ruby), and the minor version can change any moment with a breaking change.

**Comment by bbatsov** [comment]
It is the same. People consuming the gem should have added proper version boundaries, which would prevent them from using an incompatible version of the gem by accident. If they decide to update - that's a conscious decision and if they don't - nothing really changes for them.

**Comment by whitequark** [comment]
No, both of you do not understand. I do not intend to ever make a breaking API change to Parser again.

**Comment by bbatsov** [comment]
Just to clarify - breaking changes are not a bad thing; *surprising* breaking changes are a really bad thing.

**Comment by bbatsov** [comment]
> No, both of you do not understand. I do not intend to ever make a breaking API change to Parser again.

Your project, your rules. I voiced my point of view and you're totally free to disregard it. "If we all think the same way nobody thinks at all..." :-)

**Comment by whitequark** [comment]
I mean, any considerations about my versioning policy do not matter, *because* I don't intend to make a breaking change.

**Comment by mbj** [comment]
> No, both of you do not understand. I do not intend to ever make a breaking API change to Parser again.

IMO thats not a good decision. Because adding options increases the amount of complexity downstream signficiantly. If library A uses some option and library B uses another option: The amount of possible mismatch grows quadratic with the options provided. Each library that *can* consume *any* AST will now have to account for all possible combinations of options.

Parser should do "the right thing" by default (and this is representing the ruby semantics in AST) if the previous AST was broken, it should be fixed. Again your project your rules.
