### ISSUE TITLE
cannot load such file -- parser/lexer (LoadError)

### ISSUE THREAD

**Issue by bradfeehan** [whitequark/parser#282]
I'm getting this when using `BUNDLE_DISABLE_SHARED_GEMS=1` and installing `parser` (as a sub-dependency of `rubocop`). When I try to run Rubocop:

```
./vendor/bundle/ruby/2.2.0/gems/parser-2.3.0.6/lib/parser.rb:60:in `require': cannot load such file -- parser/lexer (LoadError)
	from ./vendor/bundle/ruby/2.2.0/gems/parser-2.3.0.6/lib/parser.rb:60:in `<module:Parser>'
	from ./vendor/bundle/ruby/2.2.0/gems/parser-2.3.0.6/lib/parser.rb:17:in `<top (required)>'
	from ./vendor/bundle/ruby/2.2.0/gems/rubocop-0.38.0/lib/rubocop.rb:4:in `require'
	from ./vendor/bundle/ruby/2.2.0/gems/rubocop-0.38.0/lib/rubocop.rb:4:in `<top (required)>'
	from ./vendor/bundle/ruby/2.2.0/gems/rubocop-0.38.0/bin/rubocop:7:in `require'
	from ./vendor/bundle/ruby/2.2.0/gems/rubocop-0.38.0/bin/rubocop:7:in `<top (required)>'
	from ./vendor/bundle/ruby/2.2.0/bin/rubocop:23:in `load'
	from ./vendor/bundle/ruby/2.2.0/bin/rubocop:23:in `<main>'
```

It seems if I do `gem open parser`, I can browse the source tree and find `lib/parser/lexer.rb`. However, if I do `bundle open parser` there is only `lib/parser/lexer.rl` and no `lexer.rb`.

**Comment by whitequark** [comment]
Bundler installs Parser from git (for whatever reason; I don't know how this relates to `BUNDLE_INSTALL_SHARED_GEMS`). This is not supported.

**Comment by bradfeehan** [comment]
> Bundler installs Parser from git (for whatever reason)

Is this right? When I run `bundle install` I see it talks to RubyGems.org, so I would have assumed it was getting them from the same place as `gem install`.

```
$ bundle
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Resolving dependencies...
```

So it's not supported at all to install `parser` (or any gem which depends on `parser`) using Bundler?

**Comment by whitequark** [comment]
It's perfectly fine to install Parser using Bundler. Note though:

> However, if I do bundle open parser there is only lib/parser/lexer.rl and no lexer.rb.

This cannot happen if you are installing from http://rubygems.org, because every single `.gem` file uploaded there includes `lexer.rb`. I can only conclude that Bundler is somehow picking up a git checkout of Parser.

**Comment by kidbrax** [comment]
I have this same issue. I am using Bundler as well.

**Comment by whitequark** [comment]
Don't use git checkouts of Parser, this is not supported.

**Comment by kidbrax** [comment]
If I understand Bundler correctly, that means you can't use Parser if you are fully caching (--deployment) your gems, correct? Since it pulls down everything from git and stores it locally?

**Comment by whitequark** [comment]
As far as I know that mode pulls `.gem` files from the configured sources, not from git. There isn't even a git repository specified in the [gemspec](https://github.com/whitequark/parser/blob/master/parser.gemspec)!

**Comment by celsoMartins** [comment]
Hi.

I'll use this thread because it is the only place on the WEB where I was able to find some information.

When you're caching your gems in vendor/bundle to optimize the "build" time in tools such as circle ci, travis, and google actions, for some reason, the files in the gem folder are in a .gitignore (that I could not find). So, I used the Rubymine to add these files to the git tree and pushed them. All the CIs are working now with cached gems.

<img width="1376" alt="github-action-working" src="https://user-images.githubusercontent.com/214322/94096233-f823c800-fdf9-11ea-98c3-b4c5b986e59f.png">
<img width="1278" alt="google-action-failing" src="https://user-images.githubusercontent.com/214322/94096238-fb1eb880-fdf9-11ea-82ef-6628be0d1e94.png">
<img width="792" alt="last_two_commits" src="https://user-images.githubusercontent.com/214322/94096243-fc4fe580-fdf9-11ea-8422-1473732310cd.png">
<img width="231" alt="missing-files-in-rubymine" src="https://user-images.githubusercontent.com/214322/94096244-fce87c00-fdf9-11ea-97a5-c2db5fbf8122.png">

**Comment by iliabylich** [comment]
Right, packaged version of parser includes `.gitignore`:
```
$ wget https://rubygems.org/gems/parser-2.7.1.4.gem
$ gem unpack parser-2.7.1.4.gem
$ ls -a parser-2.7.1.4 | grep gitignore
.gitignore
```

[which includes all parsers and lexer](https://github.com/whitequark/parser/blob/master/.gitignore).

I guess we could fix it by excluding `.gitignore` from the filelist here - https://github.com/whitequark/parser/blob/master/parser.gemspec#L23.

I'll fix it, for now you can manually drop this `.gitignore` file locally (however it seems that you were able to commit all parser/lexer files)

**Comment by celsoMartins** [comment]
Yes, I was.

My problem was solved.

Thanks for your work on the definitive solution.
