### ISSUE TITLE
parse chokes on escaped string

### ISSUE THREAD

**Issue by mjago** [whitequark/parser#323]
Parser::CurrentRuby.parse("x\234K\313\317\a\000\002\202\001E") fails with "invalid byte sequence in UTF-8 (EncodingError)", yet MRI and other rubies parse ok.

The string is straight from ruby/specs - there are several more similar strings that don't parse.

**Comment by whitequark** [comment]
First, this is incorrect: Ruby MRI will not parse the source code that you are parsing since version 2.0:
```
> File.write("foo.rb", "x\234K\313\317\a\000\002\202\001E")
=> 11
$ ruby foo.rb
foo.rb:1: invalid multibyte char (UTF-8)
```

If you have meant `Parser::CurrentRuby.parse('"x\234K\313\317\a\000\002\202\001E"')` instead, that is a string literal with these escape sequences verbatim, then this is not supported by default; not through any inherent limitation of Parser but the fact that creating such strings in ASCII-8BIT encoding is not generally helpful to downstream code. In case you do need to parse such strings, you should create a custom builder and override the `string_value` error:

```
require 'parser/current'
class PermissiveASTBuilder < Parser::Builders::Default
  def string_value(x) x end
end
parser = Parser::CurrentRuby.new(PermissiveASTBuilder.new)
buffer = Parser::Source::Buffer.new('(input)')
buffer.source = '"x\234K\313\317\a\000\002\202\001E"'
ast = parser.parse(buffer)
p ast # => s(:str, "x\x9CK\xCB\xCF\a\u0000\u0002\x82\u0001E")
str, = ast
p str.valid_encoding? # => false
```

**Comment by mjago** [comment]
@whitequark 
```ruby
File.open("foo.rb", 'w') {|f| f.write "x\234K\313\317\a\000\002\202\001E"}
File.open("foo.rb", 'r') {|f| p f.read.unpack('C*')}
# => [120, 156, 75, 203, 207, 7, 0, 2, 130, 1, 69]

str = "x\234K\313\317\a\000\002\202\001E"
x = str.unpack('C*')
p x    
# => [120, 156, 75, 203, 207, 7, 0, 2, 130, 1, 69]

x = Zlib::Deflate.deflate("x\234K\313\317\a\000\002\202\001E")
p (Zlib::Inflate.inflate x).unpack('C*')
# => [120, 156, 75, 203, 207, 7, 0, 2, 130, 1, 69]

ruby -v
# => ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin12.0]
```
No other parser out of all the rubies blows itself up by attempting to parse this (and 10 other) strings. It's unfortunate since parser appears to parse all other 30000 odd specs just fine!

**Comment by whitequark** [comment]
Please read my reply again.

**Comment by eregon** [comment]
From the readme, there is a note on this:
```
https://github.com/whitequark/parser#invalid-characters-inside-comments-and-literals
```

**Comment by eregon** [comment]
From the README:
```
It recognizes as much or more code than Ripper, Melbourne, JRubyParser or ruby_parser
```
At least two of those would support this.

But then there is a note on this:
https://github.com/whitequark/parser#invalid-characters-inside-comments-and-literals

> Ruby MRI permits arbitrary non-7-bit byte sequences to appear in comments, as well as in string or symbol literals in form of escape sequences, regardless of source encoding. Parser requires all source code, including the expanded escape sequences, to consist of valid byte sequences in the source encoding that are convertible to UTF-8.

So that's documented and seems an intentional choice, fair enough.
It seems like it's the most common incompatibility of the ones listed though.

It still seems very surprising to me that ***escaped*** characters are validated with the encoding.
It would also mean that something like this:
```ruby
buf = "x\234".b
```
would also not parse, even though the intention is clear.
And any binary string nicely printed with `#inspect` copy-pasted in the source (by default UTF-8) would potentially fail to parse as well.
Therefore it seems binary strings would need to be incorporated as an array of bytes + `pack` in source code to work with the default `parser`, which is not as convenient.

Thank you for showing a workaround!

**Comment by whitequark** [comment]
> It still seems very surprising to me that escaped characters are validated with the encoding.

This is unfortunately in line with the Ruby behavior. For example, if one constructs UTF-8 codepoints using `\x??` or even `\M-\c-?` escape sequences, the result will be a valid UTF-8-encoded string.

> It would also mean that something like this:
> 
> buf = "x\234".b
> would also not parse, even though the intention is clear.
> And any binary string nicely printed with #inspect copy-pasted in the source (by default UTF-8) would potentially fail to parse as well.
> Therefore it seems binary strings would need to be incorporated as an array of bytes + pack in source code to work with the default parser, which is not as convenient.

All of this is accurate. To elaborate, whereas Ruby implementations must unquestionably accept all valid Ruby code as their primary purpose is to run it, Parser is a tooling-grade parser, and its primary purpose is to enable tools to gain insight into Ruby source. As it follows, most of such tools assume that they can trust strings received from Parser, since having invalid UTF-8 in string literals is a rather rare case, and Parser, by default, lets them do so safely.

The key difference in the context. In the cases where Ruby code intentionally uses a string for binary data, such unusual code is written with this context in mind. But most source-level tools won't have this context.

> It seems like it's the most common incompatibility of the ones listed though.

Hypothetically speaking, if this were common then Parser would have adopted a different AST format for strings. But in fact, the *only* times it came up in real-world code so far (during my internal testing, which prompted the README note, as well as in coordination with the Rubocop team) is in various forms of specs for the Ruby language. It is likely still most common, but I feel like I made the choice of the default correctly here.

**Comment by csabahenk** [comment]
Hi @whitequark, the workarond you suggest in https://github.com/whitequark/parser/issues/323#issuecomment-253606403 is  not entirely correct (with current Parser at least).

Instead of this:

```ruby
class PermissiveASTBuilder < Parser::Builders::Default
  def string_value(x) x end
end
```

I think this is the right one:

```ruby
class PermissiveASTBuilder < Parser::Builders::Default
  def string_value(x) x[1] end
end
```
