### ISSUE TITLE
Odd multiple replacement rules

### ISSUE THREAD

**Issue by marcandre** [whitequark/parser#402]
I had assumed that clobbering errors were independent of the text itself (either the source or the new texts), but that's not the case. I don't understand: in which cases is that useful?

For example it is allowed to do replacements on intersecting ranges if the replacing texts matches according to a certain logic.
```
    assert_equal 'foo 123456 baz',
                 @rewriter.
                   replace(range(4, 2), '12345').
                   replace(range(5, 2), '23456').
                   process
```

To me, the code above is asking to replace `ba` with `12345` and `az` with `23456`. The rewriter is allowing it, deciding that the `b` is replaced by `1`, the `a` by `2345` and the `z` by `6`. I have no idea why it is making this assumption and not raising a clobbering error.

Moreover, it's not being consistent. If I add the redundant rules:
```
  ...
                   replace(range(4, 1), '1').
                   replace(range(5, 1), '2345').
```

These do no create a clobbering error. But somehow adding the `z => 6` rule does?
```
  ...
                   replace(range(6, 1), '6'). # => Clobbering error
```

FInally, if this was really desired, why not allow other possibilities, say like replacing the `b` with `123`, the `a` with `4` and the `r` with `567`:

```
                   replace(range(4, 2), '1234').
                   replace(range(5, 2), '4567'). # => clobbering error, not 'foo 1234567 baz'
```

**Comment by alexdowad** [comment]
I designed the current rules for Rewrite, so if I rack my brains I may be
able to remember what the intention was. However I am just traveling for
work and time is very limited. I'll see whether it may be possible to have
a look at some point.

On Nov 20, 2017 11:42 PM, "Marc-André Lafortune" <notifications@github.com>
wrote:

I had assumed that clobbering errors were independent of the text itself
(either the source or the new texts), but that's not the case. I don't
understand: in which cases is that useful?

For example it is allowed to do replacements on intersecting ranges if the
replacing texts matches according to a certain logic.

    assert_equal 'foo 123456 baz',
                 @rewriter.
                   replace(range(4, 2), '12345').
                   replace(range(5, 2), '23456').
                   process

To me, the code above is asking to replace ba with 12345 and az with 23456.
The rewriter is allowing it, deciding that the b is replaced by 1, the a by
2345 and the z by 6. I have no idea why it is making this assumption and
not raising a clobbering error.

Moreover, it's not being consistent. If I add the redundant rules:

  ...
                   replace(range(4, 1), '1').
                   replace(range(5, 1), '2345').

These do no create a clobbering error. But somehow adding the z => 6 rule
does?

  ...
                   replace(range(6, 1), '6'). # => Clobbering error

FInally, if this was really desired, why not allow other possibilities, say
like replacing the b with 123, the a with 4 and the r with 567:

                   replace(range(4, 2), '1234').
                   replace(range(5, 2), '4567'). # => clobbering
error, not 'foo 1234567 baz'

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/whitequark/parser/issues/402>, or mute the thread

**Comment by alexdowad** [comment]
Fine questions, these! They are answered in my (encyclopedic) comment on #401. But if you want more...

I am sure you saw the following comment in the `Rewriter` source:

```
      # - Insertion ("replacing" a zero-length range):
      #   - Two insertions at the same point conflict. This is true even
      #     if the earlier insertion has already been merged with an adjacent
      #     update, and even if they are both inserting the same text.
      #   - An insertion never conflicts with a replace or remove operation
      #     on its right or left side, which does not overlap it (in other
      #     words, which does not update BOTH its right and left sides).
      #   - An insertion always conflicts with a remove operation which spans
      #     both its sides.
      #   - An insertion conflicts with a replace operation which spans both its
      #     sides, unless the replacement text is longer than the replaced text
      #     by the size of the insertion (or more), and the portion of
      #     replacement text immediately after the insertion position is
      #     identical to the inserted text.
      #
      # - Removal operations never conflict with each other.
      #
      # - Replacement operations:
      #   - Take the portion of each replacement text which falls within:
      #     - The other operation's replaced region
      #     - The other operation's replacement text, if it extends past the
      #       end of its own replaced region (in other words, if the replacement
      #       text is longer than the text it replaces)
      #   - If and only if the taken texts are identical for both operations,
      #     they do not conflict.
```

These rules were designed to:

1) Never contradict one another
2) Fully specify exactly which edits will and will not conflict
3) Produce desired results in various cases which were considered important (for example, "replacing the same range with the same text does not cause a conflict")

The case which @marcandre is asking about above is not one of the "cases which were considered important". It is a corner case, and while the behavior in question is a result of the above rules, the rules were not specifically chosen to create this behavior.

I do think it necessary to apply a well-defined set of rules consistently even in such corner cases. Although @marcandre has commented that the current behavior is "inconsistent", it is actually very consistent; it is no more and no less than what the rules call for.

But the rules could be different. If a better set of rules is found, then let's change them.

@whitequark has commented before that Parser never breaks APIs. I admire him for this principled stance. But personally, I do not care if the behavior of `Rewriter` changes *in corner cases*. But I do care that whatever it is, it should be consistent, it should follow specific rules, and those rules should be possible to describe concisely. And they should be documented in precise and terse prose. It should not be necessary to scrutinize the code to figure out what they are.

**Comment by whitequark** [comment]
> @whitequark has commented before that Parser never breaks APIs.

If it's not documented or specified in any clear way whatsoever, and unlikely to result in breakage of downstream code, it's fine. But the very first change we discussed was more intrusive than that, I believe.

**Comment by marcandre** [comment]
TreeRewriter has landed, closing now.
