### ISSUE TITLE
2.5.0.1 regression

### ISSUE THREAD

**Issue by rubys** [whitequark/parser#452]
Test case:

```
require 'parser/current'
content = <<-EOF
  td (1_500).toString()
  td.num do
  end
EOF
p Parser::CurrentRuby.parse(content)
```

**Comment by iliabylich** [comment]
@whitequark `cmdarg` is not empty after the first line. 

The rule
```
| tLPAREN_ARG
    {
      result = @lexer.cmdarg.dup
      @lexer.cmdarg.clear
    }
    stmt
    {
      @lexer.state = :expr_endarg
    }
    rparen
    {
      @lexer.cmdarg = val[1]

      result = @builder.begin(val[0], val[2], val[4])
    }
```

After lexing `tLPAREN_ARG` stack is `10` (1 for `td ...` and 0 for `(1_500)`). The parser saves it, so the lexer does `cmdarg.pop` on the copy in the `)` action. Later parser restores `10` after `rparen`.

I've added
``` ruby
    assert_equal parser.instance_eval { @lexer }.cmdarg.instance_eval { @stack }, 0,
      "(#{version}) expected cmdarg to be empty after parsing"
```
in the end of the `assert_parses` method and got 9 failures.

Removing `@lexer.cmdarg.clear` and `@lexer.cmdarg = val[1]` from the code above (save/restore mechanism) solves the issue and fixes all tests, but is it a good solution? The reason why I'm asking is that it completely drops the action between `tLPAREN_ARG` and `stmt` rules which introduces a small difference between MRI and parser. Is it worth it?

**Comment by whitequark** [comment]
> Is it worth it?

That probably just introduces bugs somewhere else.

**Comment by rubys** [comment]
Probably obvious to both of you by now, but I thought I would share the output of git bisect:

```
a4fc650a47bcd5d859bb42687209a0ca27fafc35 is the first bad commit
commit a4fc650a47bcd5d859bb42687209a0ca27fafc35
Author: Ilya Bylich <ibylich@gmail.com>
Date:   Mon Feb 19 21:09:48 2018 +0300

    Fixed cmdarg manipulation in command_args rule.

:040000 040000 780e9314c9312ce09d9b1b90a9599005141f3375 b8468cd181196f5a3bd1cc3e3fa976c2115361d3 M	lib
:040000 040000 3f76e89e7ebba50305c90ba03d9c355afbc8cc0e 7ca363ff35a07c4132e3c6bfefb36a51ce94f283 M	test
bisect run success
```

**Comment by iliabylich** [comment]
After full backporting of MRI's `cmdarg` implementation parser can't handle cases like `a b(c d), "x" do end`.

And the reason is that in MRI `CMDARG_P` (predicate, I guess) returns `false` on parsing `do`. So after "x" MRI's lexer goes to the dual-state `EXPR_END|EXPR_ENDARG` (which looks like a hack to me) to later catch it in the next section of 'do' parsing that does:
``` c

if (CMDARG_P() && !IS_lex_state_for(state, EXPR_CMDARG)) // false
  return keyword_do_block
if (IS_lex_state_for(state, (EXPR_BEG | EXPR_ENDARG))) // true
  return keyword_do_block // <- this line emits kDO_BLOCK
```

Ragel doesn't support it, so I have no ideas how to backport it without changes.
I've created a ticket in MRI's redmine - https://bugs.ruby-lang.org/issues/14506.
Right now I don't see how can we replicate MRI's behavior without re-writing cmdarg handling to what I've described in https://github.com/whitequark/parser/issues/452#issuecomment-367373555.

**Comment by iliabylich** [comment]
I guess I can't backport it as is, but probably we could change MRI - https://github.com/ruby/ruby/pull/1823

**Comment by iliabylich** [comment]
It was merged in https://github.com/ruby/ruby/commit/1727c8358498054428a376b52869983549f62399, I'll prepare a corresponding patch for the `parser`. Now we can backport it without any changes.

**Comment by whitequark** [comment]
Thanks!
