### ISSUE TITLE
RSpec warning

### ISSUE THREAD

**Issue by MicMicMon** [whitequark/parser#662]
When running RSpec with warnings enabled on my project (I don't use `parser` but I guess it's a peer dependency), I get a warning:
```sh
/home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/parser-2.7.0.5/lib/parser/lexer.rb:10991: warning: assigned but unused variable - testEof
```

I guess it's complicated to fix since it may be autogenerated code (guessing from the line number). Still throwing that out there if there's an easy fix :)

**Comment by iliabylich** [comment]
Previously discussed here - https://github.com/whitequark/parser/issues/360.

Yes, you are right, it comes from the generated code. Probably could be fixed by removing an assignment here - https://github.com/whitequark/parser/blob/master/Rakefile#L152 but I'm knot sure if it's worth it. It's just a warning in verbose mode.
