### ISSUE TITLE
2.6.6 release

### ISSUE THREAD

**Issue by jwilsjustin** [whitequark/parser#663]
Ruby 2.6.6 was released. https://www.ruby-lang.org/en/news/2020/03/31/ruby-2-6-6-released/

Does anyone know if there are any changes that will affect the parser gem? Any chances we could get a 2.6.6 release pushed to rubygems?

**Comment by iliabylich** [comment]
No, 2.6.6 is a security release, so there are no changes to the grammar.
However, 2.4.10, 2.5.8 and 2.7.1 have been released, and 2.7.1 has this change - https://github.com/whitequark/parser/issues/656 that has to be backported first.

I'll do it later today and then I'll cut a release.

**Comment by iliabylich** [comment]
@jwilsjustin parser `2.7.1.0` has been released - https://rubygems.org/gems/parser/versions/2.7.1.0

**Comment by jwilsjustin** [comment]
Thanks for your quick work @iliabylich! I was hoping for a 2.6.6 version. Do you mind releasing that version to rubygems?

**Comment by iliabylich** [comment]
parser 2.7.1.0 should parse 2.6.6 syntax. We have only 1 branch and so we don't make releases specifically for old versions of ruby.

In general the rule is that if you are on ruby X.Y.Z and:
+ Z is the latest patch version of ruby (i.e. there's no `X.Y.Z+1`) then you should simply use the latest available version of parser (2.7.1.0 in this particular case)
+ otherwise, you should use parser `X.Y.Z.<latest>`

If you need a parser for ruby 2.6.6 just use the latest release

**Comment by jwilsjustin** [comment]
Thanks @iliabylich !
