### ISSUE TITLE
parser emitting warnings

### ISSUE THREAD

**Issue by mperham** [whitequark/parser#684]
Can I request turning on warnings?  My test suite emits these warnings from parser:

/Users/mikeperham/.gem/ruby/2.7.1/gems/parser-2.7.1.2/lib/parser/source/tree_rewriter.rb:235: warning: mismatched indentations at 'end' with 'def' at 224
/Users/mikeperham/.gem/ruby/2.7.1/gems/parser-2.7.1.2/lib/parser/lexer.rb:10991: warning: assigned but unused variable - testEof

https://github.com/whitequark/parser/blob/master/Rakefile#L14

**Comment by iliabylich** [comment]
The first warning definitely can be fixed. The second one comes from the generated code that we don't own.

I guess we could easily fix it by adding something like 
```ruby
if false
  testEof
end
```
At the bottom of `Lexer#advance`. It will have no runtime cost because Ruby starting from 2.5 has some basic DCE (at least for `if false/unless true`):
```
> ruby --dump=insns -e 'a = 1'
== disasm: #<ISeq:<main>@-e:1 (1,0)-(1,5)> (catch: FALSE)
local table (size: 1, argc: 0 [opts: 0, rest: -1, post: 0, block: -1, kw: -1@-1, kwrest: -1])
[ 1] a@0
0000 putobject_INT2FIX_1_                                             (   1)[Li]
0001 dup
0002 setlocal_WC_0                a@0
0004 leave

> ruby --dump=insns -e 'a = 1; if false; a; end'
== disasm: #<ISeq:<main>@-e:1 (1,0)-(1,23)> (catch: FALSE)
local table (size: 1, argc: 0 [opts: 0, rest: -1, post: 0, block: -1, kw: -1@-1, kwrest: -1])
[ 1] a@0
0000 putobject_INT2FIX_1_                                             (   1)[Li]
0001 setlocal_WC_0                a@0
0003 putnil
0004 leave
```

^ so there's an extra `putnil` that will go away because it will not be an implicit return value. Looks like a safe solution to me. I'll send a PR tomorrow.
