### ISSUE TITLE
Different behavior code parser to identical AST tree (array map)

### ISSUE THREAD

**Issue by adam429** [whitequark/parser#858]
If you run code1 and code2 in ruby, it get different result.

But when parser to AST tree, the code1 AST tree is identical to code 2 AST tree.

```
require 'parser/current'

code1 = "[[1,2],[3,4]].map {|x| x}"
puts eval(code1) == [[1,2],[3,4]]   #==> true

code2 = "[[1,2],[3,4]].map {|x,| x}"
puts eval(code2) == [1,3]   # ==> true

ast1 = Parser::CurrentRuby.parse(code1)
ast2 = Parser::CurrentRuby.parse(code2)

puts ast1 == ast2  #=> true

puts ast1
# s(:block,
#     s(:send,
#       s(:array,
#         s(:array,
#           s(:int, 1),
#           s(:int, 2)),
#         s(:array,
#           s(:int, 3),
#           s(:int, 4))), :map),
#     s(:args,
#       s(:arg, :x)),
#     s(:lvar, :x))

puts ast2
# s(:block,
#     s(:send,
#       s(:array,
#         s(:array,
#           s(:int, 1),
#           s(:int, 2)),
#         s(:array,
#           s(:int, 3),
#           s(:int, 4))), :map),
#     s(:args,
#       s(:arg, :x)),
#     s(:lvar, :x))
```

**Comment by iliabylich** [comment]
Yes, you probably want to "modernize" an AST builder:

```ruby
Parser::Builders::Default.modernize
```

Or (more specifically) enable a single flag:

```ruby
Parser::Builders::Default.emit_procarg0 = true
```

I'd strongly recommend enabling all of them unless you have a huge codebase that relies on the "old" format of the AST.

**Comment by iliabylich** [comment]
I agree, but that would be a breaking change that current versioning system doesn't support.

Do you see a way to automatically enable "modern" mode and keep it compatible? Adding another class (`ModernRubyXY`?) or an extra option to a `Parser` class doesn't change the whole picture, existing users don't pass any extra options or flags anyway.

Also, compatibility flags is the only way to keep AST format compatible and be capable of emitting a new AST at the same time if needed. Sometimes we have to introduce breaking changes because of existing bugs or misunderstanding of Ruby (and this `procarg0` node is a good example). We will have to do it again in the future and so we have to either change versioning to semver (which is a HUGE breaking change) or keep it always-backward-compatible and add new flags (which returns us back to the original problem).

I agree that there's a problem but honestly I don't know how to fix it without breaking everything first.

**Comment by marcandre** [comment]
FWIW, RuboCop made specific choices on the switches; we have two turned on (`emit_forward_arg` and `emit_match_pattern`), everything else is off.

The `rubocop-ast` gem, which is a layer on top of `parser` and adds things like the node pattern is compatible with all combinations of switches.

**Comment by marcandre** [comment]
My personal opinion is that some of those switches are really "in retrospect, we made a mistake and we're fixing it with this switch", others are "there's a theoretical difference between these, but not a practical one" (I'm thinking of lambda, which is counter productive to turn on for linting tools like `rubocop`), and some are in between (like `emit_proc0`) that really depends on what the tool using `parser` wants to do.

**Comment by marcandre** [comment]
I should have mentioned, but `rubocop` would break if a user somehow where to upgrade `parser` but not `rubocop`, as gem requirement is `>= some_version`.

**Comment by palkan** [comment]
I'm not sure preventing such mistakes worth a breaking change. Instead, we can make it clearer in the documentation and, maybe, add a simpler API to _modernize_. We do not expect developers to start using Parser without looking at the Readme first, right?

So, right now we have:


Load Parser (see the [backwards compatibility](https://github.com/whitequark/parser/issues/858#backwards-compatibility) section below for explanation of emit_* calls):

```ruby
require 'parser/current'
# opt-in to most recent AST format:
Parser::Builders::Default.emit_lambda              = true
Parser::Builders::Default.emit_procarg0            = true
Parser::Builders::Default.emit_encoding            = true
Parser::Builders::Default.emit_index               = true
Parser::Builders::Default.emit_arg_inside_procarg0 = true
Parser::Builders::Default.emit_forward_arg         = true
Parser::Builders::Default.emit_kwargs              = true
Parser::Builders::Default.emit_match_pattern       = true
```

What if we change to something like:

Load Parser:

```ruby
require 'parser/current'
require 'parser/modernize' # use the most recent AST format
```

Instead of using the modern AST format and requiring `parser/modernize`, you can configure it yourself (see the [backwards compatibility](https://github.com/whitequark/parser/issues/858#backwards-compatibility) section below).
